backend:
  name: git-gateway
  branch: master  # o la rama que uses

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "docs"
    label: "Documentación"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    extension: "mdx"  # o "md" si no usas MDX
    nested:           # Habilita la visualización de subcarpetas
      depth: 10       # Define la profundidad máxima de subcarpetas
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
      - { label: "Etiquetas", name: "tags", widget: "list" }
      - { label: "sidebar_position", name: "sidebar_position", widget: "Number" }
  - name: "ReleaseNotes"
    label: "Release Notes"
    folder: "/ReleaseNotes"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    extension: "mdx"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
      - { label: "Etiquetas", name: "tags", widget: "list" }
      - { label: "sidebar_position", name: "sidebar_position", widget: "Number" }